services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: plantbase
      POSTGRES_USER: plantbase
      POSTGRES_PASSWORD: plantbase
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U plantbase -d plantbase']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
